import { StyleSheet, Text, View,TouchableOpacity,Image } from 'react-native'
import React from 'react'

const TermnConditions = ({navigation}) => {
  return (
    <View style={{backgroundColor:'black',height:900}}>
       <TouchableOpacity  onPress={() => navigation.navigate('Refer')} >
    
    <Image style={{marginLeft:20,top: 20,}}
    source={require('../../../assets/back1.png')} />
   
   </TouchableOpacity>
      <Text style={{fontWeight:600,fontSize:25,color:'white',top: 40,left:20}}>Terms and Conditions</Text>
      <Text style={{fontWeight:400,fontSize:14,color:'white',top: 50,left:20,width:340}}>This document is an electronic record in terms of the Information Technology Act, 2000 (“Act”), amendments thereof from time to time, rules thereunder as applicable and amended provisions pertaining to electronic records in various statutes as amended by the Act. This electronic record is generated by a computer system and does not require physical or digital signatures.

<Text style={{lineHeight:23,}}>Please read these terms and conditions (“Terms”) carefully before registering, accessing, using, or participating in ‘Bc app ’ (defined below). These Terms govern Your access to, participation in, usage of BC app and constitute a legally binding agreement between You and BC App Private Limited, having its registered office at Office-xyz, Floor xyz, Wing ABC, Block ABC, Salarpuria Softzone XYZ, Service Road, Green Glen Layout, Bellandur, Bengaluru, Karnataka – 560103, India. </Text>

All references to ‘BC APP’ under these Terms shall be deemed to mean and include its affiliates, associates, subsidiaries, group companies, their respective officers, directors, employees, representatives, and agents. You agree and acknowledge that You have read these Terms and if You do not agree to or wish to be bound by these Terms, You shall not access, participate in, or use BC App Earn in any manner whatsoever. You also understand that additionally all other website policies, general or product specific terms and conditions. <Text style={{color:'blue'}}>Read More..</Text></Text>

    </View>
  )
}

export default TermnConditions

const styles = StyleSheet.create({})